project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands_on_Ex1.html
          - text: Hands-on Exercise 2
            href: Hands_on_Ex2.html
          - text: Hands-on Exercise 3
            href: Hands_on_Ex3.html
          - text: Hands-on Exercise 3 PASG
            href: Hands_on_Ex3_2.html
          - text: Hands-on Exercise 4
            href: Hands_on_Ex4.html
          - text: Hands-on Exercise 4 VSA
            href: Hands_on_Ex4_VSA.html
          - text: Hands-on Exercise 4 VU
            href: Hands_on_Ex4_VU.html
          - text: Hands-on Exercise 4 FPFFC
            href: Hands_on_Ex4_FPFFC.html
          - text: Hands-on Exercise 5 CTP
            href: Hands_on_Ex5_CTP.html
          - text: Hands-on Exercise 5 VCA
            href: Hands_on_Ex5_VCA.html
          - text: Hands-on Exercise 5 HVAMD
            href: Hands_on_Ex5_HVAMD.html
          - text: Hands-on Exercise 5 VMAPCP
            href: Hands_on_Ex5_VMAPCP.html
          - text: Hands-on Exercise 5 TV
            href: Hands_on_Ex5_TV.html
          - text: Hands-on Exercise 6
            href: Hands_on_Ex6.html
      - text: In-class Exercise
        menu: 
          - text: In-class Exercise 1
            href: In_class_Ex1.html
          - text: In-class Exercise 2
            href: In_class_Ex2.html
      - text: Take-home Exercise
        menu: 
          - text: Take-home Exercise 1
            href: Take_home_Ex1.html
          - text: Take-home Exercise 2
            href: Take_home_Ex2.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

